spring:
    application:
        name: Akkadian Lexicon
    profiles:
        active: ${ENVIRONMENT}
registration:
    tokenExpirationDayCount: 1
    confirmationUrlPath: /users/registrationConfirm
server:
    port: ${WEBSERVER_PORT}





